name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build  -t tinphancr7/react:v1 .
      - name: Login to Docker hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push the Docker image
        run: docker push  tinphancr7/react:v1

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: pull the docker image
        run: docker pull tinphancr7/react:v1
      - name: stop and remove the docker container
        run: |
          if docker ps -a | grep -q reactv1; then
          docker stop reactv1
          docker rm reactv1
          else
          echo "Container 'reactv1' does not exist."
          fi
      - name: run the docker container
        run: docker run -dp 8080:80 --name reactv1  tinphancr7/react:v1
